# Generated by Django 4.0.3 on 2022-04-06 08:53

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(help_text='feeback_name')),
                ('user_cause', models.CharField(help_text='feeback_cause', max_length=25)),
                ('user_email', models.CharField(help_text='feeback_email', max_length=25)),
                ('fund_id', models.CharField(help_text='fund_id', max_length=50, null=True)),
                ('user_feedbacks', models.TextField(help_text='feebacks', null=True)),
                ('feedback_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
        migrations.CreateModel(
            name='FundRaiserModel',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Enter Your Name')),
                ('relation', models.TextField(help_text='enter Your Relation')),
                ('phone_number', models.BigIntegerField(blank=True, help_text='enter phone number', null=True)),
                ('gmail', models.EmailField(help_text='Enter gmail', max_length=254)),
                ('upload_image', models.ImageField(upload_to='images/')),
                ('upload_doc', models.ImageField(upload_to='document/images/')),
                ('upload_proof', models.ImageField(upload_to='proof/images/')),
                ('describtion', models.TextField(help_text='Enter describtion ', max_length=500)),
                ('title', models.CharField(help_text='Enter tittle', max_length=50)),
                ('proof', models.CharField(help_text='Types of proof ', max_length=50)),
                ('document_verification', models.CharField(help_text='Enter document_verification', max_length=50)),
                ('currency', models.CharField(blank=True, help_text='currency', max_length=100, null=True)),
                ('fund_price', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('cause', models.TextField(help_text='cause', null=True)),
                ('raisefundfor', models.TextField(help_text='raisefundfor', null=True)),
                ('status', models.TextField(default='pendding', null=True)),
                ('submitted_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'fund_raiser_details',
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Enter Your Name', null=True)),
                ('gmail', models.EmailField(help_text='Enter Gmail Here', max_length=254, null=True)),
                ('country', models.CharField(help_text='Enter country here', max_length=200)),
                ('phno', models.BigIntegerField()),
                ('payment_date', models.DateField(auto_now_add=True, null=True)),
                ('cardnumber', models.CharField(help_text='cardnumber', max_length=15, null=True)),
                ('cardholder_name', models.TextField(help_text='Enter Your Name', null=True)),
                ('startmonth', models.CharField(help_text='start', max_length=15, null=True)),
                ('expiarydate', models.CharField(help_text='expirydate', max_length=15, null=True)),
                ('cvv', models.CharField(help_text='cvv', max_length=15, null=True)),
                ('fund_id', models.CharField(help_text='fund_id', max_length=50, null=True)),
                ('selectbank', models.CharField(help_text='selectbank', max_length=50, null=True)),
                ('username', models.CharField(help_text='username', max_length=50, null=True)),
                ('password', models.CharField(help_text='password', max_length=50, null=True)),
                ('amount', models.CharField(help_text='amount', max_length=50, null=True)),
            ],
            options={
                'db_table': 'payment_details',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('signup_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Enter Your Name', max_length=50)),
                ('gmail', models.EmailField(help_text='Enter gmail', max_length=50)),
                ('password', models.CharField(help_text='enter Password', max_length=200)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
