# Generated by Django 4.0.3 on 2022-04-06 11:04

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_fundraisermodel_fund_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisermodel',
            name='fund_price',
            field=models.BigIntegerField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.BigIntegerField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
