# Generated by Django 4.0.3 on 2022-04-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_fundraisermodel_fund_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisermodel',
            name='fund_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
