# Generated by Django 4.0.3 on 2022-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_fundraisermodel_fund_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisermodel',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
    ]
