# Generated by Django 4.0.3 on 2022-04-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_rename_data3_paymentmodel_fund_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='submitted_date',
            new_name='submitted_date2',
        ),
    ]
