# Generated by Django 4.0.3 on 2022-04-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_rename_submitted_date_paymentmodel_submitted_date2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='fund_price',
            new_name='fund_price2',
        ),
    ]
