# Generated by Django 4.0.3 on 2022-04-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_remove_paymentmodel_fund_price2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='fund_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.fundraisermodel'),
        ),
    ]
