# Generated by Django 4.0.3 on 2022-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_remove_paymentmodel_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='fund_id',
            field=models.CharField(help_text='fund_id', max_length=50, null=True),
        ),
    ]
