# Generated by Django 4.0.3 on 2022-04-08 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_paymentmodel_cvv_paymentmodel_expiarydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='fund_price2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.fundraisermodel'),
        ),
    ]
