# Generated by Django 4.0.3 on 2022-04-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_remove_paymentmodel_fund_price2'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='fund_price2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.fundraisermodel'),
        ),
    ]
