# Generated by Django 4.0.3 on 2022-04-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_alter_paymentmodel_fund_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='cardholder_name',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='cardnumber',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='expiarydate',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='selectbank',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='startmonth',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='submitted_date2',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='username',
        ),
    ]
