# Generated by Django 4.0.3 on 2022-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_remove_paymentmodel_cardholder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='cardholder_name',
            field=models.TextField(help_text='Enter Your Name', null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='cardnumber',
            field=models.CharField(help_text='cardnumber', max_length=15, null=True),
        ),
    ]
