# Generated by Django 4.0.3 on 2022-04-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_paymentmodel_cardholder_name_paymentmodel_cardnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='country',
            new_name='gender',
        ),
    ]
