# Generated by Django 4.0.3 on 2022-04-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_rename_country_paymentmodel_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraisermodel',
            old_name='currency',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='gender',
            new_name='country',
        ),
    ]
