# Generated by Django 4.1.3 on 2022-12-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_rename_currency_fundraisermodel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisermodel',
            name='fund_raiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel'),
        ),
    ]
