# Generated by Django 4.1.3 on 2022-12-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_fundraisermodel_fund_raiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
