# Generated by Django 4.1.12 on 2025-02-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0030_fundraisermodel_fund_price_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisermodel',
            name='status',
            field=models.TextField(default='pending', null=True),
        ),
    ]
